typography_spectrum: 0.42619905015453696
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.1436648922972381
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5054525048471987
analytics:
  google: null
  facebook: null
  twitter: null
name: gaird
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: 'Been there, done that'
purpose: []
